# ------ root_path/dataset_name ------
root_path: 'data_path'
prompt_path: 'prompt_path'


# ------ Load Cache and Features ------
#load_cache: False
#load_pre_feat: False

load_cache: True
load_pre_feat: True


# ------ Hyperparamters ------
search_hp: True
# search_hp: False

search_scale: [30, 30, 60]
search_step: [200, 30, 40]



# ------ Basic Config ------
dataset: 'imagenet'
shots: 2
backbone: 'RN50'

lr: 0.001
augment_epoch: 10
train_epoch: 20